### PR TITLE
Remove MMTk counted malloc

### PR DESCRIPTION
**Pull request by qinsoon**
This PR changes the implementation of malloc methods for MMTk. We no longer use malloc and counted malloc methods from MMTk for those. Instead, we maintain a global counter for the size, and report the size to MMTk.

### CODE REVIEW

**Review by udesou — APPROVED** [review]
LGTM.

**Comment by qinsoon** [comment]
Should I move `jl_malloc_aligned` etc back to `gc.c` and `mmtk-gc.c`? In that case, we can replace the implementation of malloc without changing the interface. @udesou

**Comment by udesou** [comment]
If the intention is that we're replacing the malloc implementation in the future, then I agree that it shouldn't be in `gc-common.c`. The question is whether we're doing that or not.

**Comment by qinsoon** [comment]
> If the intention is that we're replacing the malloc implementation in the future, then I agree that it shouldn't be in `gc-common.c`. The question is whether we're doing that or not.

I will make that change in the PR. In that case, this PR does not change the interface.

**Pull request merged**
